"""initial schema

Revision ID: 213bb5ec98a1
Revises: 
Create Date: 2026-09-01 13:32:42.940524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.database.base


# revision identifiers, used by Alembic.
revision: str = '213bb5ec98a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('lifetime_value', sa.Integer(), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('days_until_cancellation', sa.Integer(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('parent_transaction_id', sa.Integer(), nullable=True),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_transactions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_transaction_id'], ['transactions.id'], name=op.f('fk_transactions_parent_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_transactions_status_created', ['status', 'created_at'], unique=False)

    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('diagnosis', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.String(length=48), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sa.String(length=48), nullable=True),
    sa.Column('amount_at_risk', sa.Integer(), nullable=False),
    sa.Column('amount_recovered', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('last_contact_at', app.database.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.database.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_recovery_cases_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_recovery_cases_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_cases'))
    )
    with op.batch_alter_table('recovery_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_cases_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_cases_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_agent_actions_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_actions'))
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_recovery_case_id'), ['recovery_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_timestamp'), ['timestamp'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timestamp', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_messages_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_recovery_case_id'), ['recovery_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_recovery_case_id'))

    op.drop_table('messages')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_recovery_case_id'))

    op.drop_table('agent_actions')
    with op.batch_alter_table('recovery_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_cases_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_cases_status'))
        batch_op.drop_index(batch_op.f('ix_recovery_cases_risk_level'))
        batch_op.drop_index(batch_op.f('ix_recovery_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_cases_created_at'))

    op.drop_table('recovery_cases')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_status_created')
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
